Add metering of local variables
ElrondNetwork/wasmer pull request #4
Opened 2020-09-04 14:54 UTC by camilbancioiu

Added the `feed_local()` method to `FunctionMiddleware`, `GenericFunctionMiddleware`, and the `Metering` middleware. Arwen must now supply an extra gas cost, for allocating a single local variable.

Tests for this change will be added to Arwen.

2020-09-04 18:15 UTC, sasurobert requested changes
Check and add the difference of gas cost for the current contracts. Adding this as it is right now it is not backward compatible. Might add these extra local variables gas cost only after 100 variables were allocated.

2020-09-07 20:11 UTC, sasurobert approved these changes

2020-09-07 20:11 UTC, sasurobert commented on lib/middleware-common/src/metering.rs
> +        println!("current local: {}", n);
why println here ? no need

2020-09-07 20:11 UTC, sasurobert requested changes
no need for println

2020-09-08 09:20 UTC, camilbancioiu commented on lib/middleware-common/src/metering.rs
> +        println!("current local: {}", n);
Accidentally forgotten. Will remove.

2020-09-08 15:15 UTC, sasurobert approved these changes

2020-09-08 17:50 UTC, merged